import { useLocalSearchParams, useRouter } from 'expo-router';
import { useMemo, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { EMPIRE_PORTS, replayEmpireBattle, starsFor, type EmpireCoord } from '@engine/empire';
import { completeEmpireBattle } from '@/empire/api';
import { InkButton } from '@/ui/InkButton'; import { Paper } from '@/ui/Paper'; import { Scale } from '@/ui/Scale'; import { color, font, type as typeScale } from '@/ui/tokens';

export default function EmpireBattleScreen() {
  const router = useRouter(); const { portId } = useLocalSearchParams<{ portId?: string }>(); const port = useMemo(() => EMPIRE_PORTS.find((p) => p.id === portId) ?? EMPIRE_PORTS[0]!, [portId]); const [shots, setShots] = useState<EmpireCoord[]>([]); const [busy, setBusy] = useState(false); const fired = new Set(shots.map((s) => `${s.row}:${s.col}`)); const occupied = new Set(port.ships.flatMap((s) => s.cells.map((c) => `${c.row}:${c.col}`))); const result = replayEmpireBattle(port, shots);
  const fire = async (cell: EmpireCoord) => { const key = `${cell.row}:${cell.col}`; if (busy || fired.has(key) || result.won) return; const next = [...shots, cell]; setShots(next); const resolved = replayEmpireBattle(port, next); if (resolved.won) { setBusy(true); try { await completeEmpireBattle(port.id, next); } finally { setBusy(false); } } };
  return <Scale><Paper variant="full" /><View style={styles.header}><InkButton label="Map" w={74} h={40} onPress={() => router.back()} /><View><Text style={styles.title}>{port.name}</Text><Text style={styles.sub}>{port.twist}{port.boss ? ` · ${port.boss}` : ''} · {shots.length} turns</Text></View><Text style={styles.stars}>{result.won ? `${starsFor(port, result)} ★` : 'Find the fleet'}</Text></View><View style={styles.board}>{Array.from({ length: 10 }, (_, row) => Array.from({ length: 10 }, (_x, col) => { const key = `${row}:${col}`; const hit = fired.has(key) && occupied.has(key); const miss = fired.has(key) && !occupied.has(key); return <Pressable key={key} accessibilityRole="button" accessibilityLabel={`Row ${row + 1}, column ${col + 1}${hit ? ', hit' : miss ? ', miss' : ''}`} disabled={busy || fired.has(key)} onPress={() => void fire({ row, col })} style={[styles.cell, { left: col * 28, top: row * 28 }]}><Text style={[styles.mark, hit && styles.hit]}>{hit ? '×' : miss ? '·' : ''}</Text></Pressable>; }))}</View>{result.won ? <Text style={styles.won}>Port conquered · your flag is raised</Text> : null}</Scale>;
}
const styles = StyleSheet.create({ header: { position: 'absolute', left: 18, right: 18, top: 10, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, title: { color: color.ink, fontFamily: font.display, fontSize: typeScale.lg, textAlign: 'center' }, sub: { color: color.inkSoft, fontFamily: font.body, fontSize: typeScale.xs }, stars: { width: 100, color: color.inkRed, fontFamily: font.label, fontSize: typeScale.sm, textAlign: 'right' }, board: { position: 'absolute', left: 260, top: 68, width: 280, height: 280, borderWidth: 2, borderColor: color.ink }, cell: { position: 'absolute', width: 28, height: 28, borderRightWidth: StyleSheet.hairlineWidth, borderBottomWidth: StyleSheet.hairlineWidth, borderColor: color.gridMajor, alignItems: 'center', justifyContent: 'center' }, mark: { color: color.inkSoft, fontFamily: font.label, fontSize: 20 }, hit: { color: color.inkRed }, won: { position: 'absolute', left: 550, top: 180, width: 220, color: color.inkGreen, fontFamily: font.display, fontSize: typeScale.md } });
