"""Probe every video/audio file in the repo (outside launch-film/) and write ASSET_INVENTORY.md."""
import json, subprocess, os, sys, statistics
ROOT = '/home/user/battleship-solana-mobile'
OUT = os.path.join(ROOT, 'launch-film', 'ASSET_INVENTORY.md')
VID = ('.mp4', '.mov', '.webm', '.mkv', '.m4v')
AUD = ('.mp3', '.wav', '.ogg', '.m4a', '.aac', '.flac')

def probe(p):
    r = subprocess.run(['ffprobe', '-v', 'error', '-print_format', 'json', '-show_format', '-show_streams', p], capture_output=True, text=True)
    return json.loads(r.stdout or '{}')

def frac(s):
    try:
        a, b = s.split('/'); return float(a) / float(b) if float(b) else 0.0
    except Exception:
        return 0.0

def vfr_check(p):
    r = subprocess.run(['ffprobe', '-v', 'error', '-select_streams', 'v:0', '-show_entries', 'packet=pts_time', '-of', 'csv=p=0', p], capture_output=True, text=True)
    ts = sorted(float(x) for x in r.stdout.split() if x.strip() not in ('', 'N/A'))
    d = [b - a for a, b in zip(ts, ts[1:]) if b - a > 0]
    if len(d) < 3: return 'n/a', 0
    med = statistics.median(d)
    spread = (max(d) - min(d)) / med if med else 0
    return ('VFR' if spread > 0.5 else 'CFR'), len(ts)

def loud(p):
    r = subprocess.run(['ffmpeg', '-hide_banner', '-nostats', '-i', p, '-af', 'ebur128=peak=true', '-f', 'null', '-'], capture_output=True, text=True)
    tail = r.stderr[r.stderr.rfind('Summary:'):]
    I = tp = None
    for line in tail.splitlines():
        line = line.strip()
        if line.startswith('I:'): I = line.split()[1]
        if line.startswith('Peak:'): tp = line.split()[1]
    return I, tp

files = []
for dp, dn, fn in os.walk(ROOT):
    if any(x in dp for x in ('/node_modules', '/.git', '/launch-film')): continue
    for f in fn:
        if f.lower().endswith(VID + AUD): files.append(os.path.join(dp, f))
files.sort()

vrows, arows = [], []
for p in files:
    j = probe(p); rel = os.path.relpath(p, ROOT)
    fmt = j.get('format', {}); dur = float(fmt.get('duration', 0) or 0)
    vs = [s for s in j.get('streams', []) if s['codec_type'] == 'video' and s.get('disposition', {}).get('attached_pic', 0) == 0]
    as_ = [s for s in j.get('streams', []) if s['codec_type'] == 'audio']
    size = os.path.getsize(p) / 1e6
    if p.lower().endswith(VID) and vs:
        v = vs[0]; w, h = v.get('width'), v.get('height')
        rot = 0
        for sd in v.get('side_data_list', []) or []:
            if 'rotation' in sd: rot = sd['rotation']
        if abs(rot) in (90, 270): w, h = h, w
        orient = 'landscape' if w > h else ('portrait' if h > w else 'square')
        rfr, afr = frac(v.get('r_frame_rate', '0/1')), frac(v.get('avg_frame_rate', '0/1'))
        cv, n = vfr_check(p)
        a = as_[0] if as_ else None
        aud = f"{a['codec_name']} {int(a.get('sample_rate', 0))/1000:g}k {a.get('channels')}ch" if a else 'none'
        vrows.append(f"| `{rel}` | {dur:.2f}s | {w}×{h} | {afr:.2f} (r {rfr:.2f}) | {cv} | {v['codec_name']} {v.get('pix_fmt','')} | {aud} | {orient} | {size:.1f} MB |")
    elif p.lower().endswith(AUD) and as_:
        a = as_[0]; I, tp = loud(p)
        arows.append(f"| `{rel}` | {dur:.2f}s | {a['codec_name']} {int(a.get('sample_rate', 0))/1000:g}k {a.get('channels')}ch | {I} LUFS | {tp} dBFS | {size*1000:.0f} KB |")
    print(rel, file=sys.stderr)

with open(OUT, 'w') as o:
    o.write('# Asset inventory\n\nGenerated by `tools/inventory.py` (ffprobe + ffmpeg ebur128). Every video and audio file in the repo outside `launch-film/`. CFR/VFR is judged from packet timestamp spread (>50 % of the median frame interval = VFR).\n\n')
    o.write(f'## Video ({len(vrows)})\n\n| Path | Duration | Resolution | fps (avg / r) | CFR/VFR | Codec | Audio | Orientation | Size |\n|---|---|---|---|---|---|---|---|---|\n')
    o.write('\n'.join(vrows) + '\n\n')
    o.write(f'## Audio ({len(arows)})\n\nLoudness = integrated LUFS; peak = true peak (dBFS).\n\n| Path | Duration | Format | Loudness | True peak | Size |\n|---|---|---|---|---|---|\n')
    o.write('\n'.join(arows) + '\n')
print('wrote', OUT)
