"""ffprobe + loudness report for the deliverables → out/REPORT.md"""
import json, os, subprocess
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'out')


def probe(p):
    return json.loads(subprocess.run(['ffprobe', '-v', 'error', '-print_format', 'json', '-show_format', '-show_streams', p], capture_output=True, text=True).stdout)


def loud(p):
    r = subprocess.run(['ffmpeg', '-hide_banner', '-nostats', '-i', p, '-af', 'ebur128=peak=true', '-f', 'null', '-'], capture_output=True, text=True).stderr
    s = r[r.rfind('Summary:'):]
    v = {}
    for line in s.splitlines():
        line = line.strip()
        for k in ('I:', 'LRA:', 'Peak:'):
            if line.startswith(k):
                v[k[:-1]] = line.split()[1]
    return v


rows = []
for name in ('EmpireOfBits_LaunchFilm_4K.mp4', 'EmpireOfBits_LaunchFilm_1080p.mp4'):
    p = os.path.join(OUT, name)
    if not os.path.exists(p):
        continue
    j = probe(p)
    v = next(s for s in j['streams'] if s['codec_type'] == 'video')
    a = next((s for s in j['streams'] if s['codec_type'] == 'audio'), {})
    dur = float(j['format']['duration'])
    fr = v['r_frame_rate']
    L = loud(p)
    rows.append(
        f"| `{name}` | {int(dur // 60)}:{dur % 60:06.3f} ({dur:.3f} s) | {v['width']}×{v['height']} | {eval(fr):.3f} ({fr}) | {v['codec_name']} {v.get('profile', '')} {v.get('pix_fmt', '')} {v.get('color_space', '')} | "
        f"{a.get('codec_name', '')} {int(a.get('bit_rate', 0)) // 1000} kb/s {a.get('sample_rate', '')} Hz {a.get('channels', '')} ch | {L.get('I')} LUFS | {L.get('Peak')} dBTP | {L.get('LRA')} LU | {os.path.getsize(p) / 1e6:.1f} MB |"
    )
imgs = []
for name in ('poster.jpg', 'thumbnail_1280x720.jpg'):
    p = os.path.join(OUT, name)
    if os.path.exists(p):
        s = next(x for x in probe(p)['streams'])
        imgs.append(f"| `{name}` | {s['width']}×{s['height']} | {os.path.getsize(p) / 1e3:.0f} KB |")
with open(os.path.join(OUT, 'REPORT.md'), 'w') as o:
    o.write('# Deliverables report\n\nGenerated by `tools/report.py` (ffprobe + ffmpeg ebur128 with true peak).\n\n')
    o.write('| File | Duration | Resolution | fps | Video | Audio | Integrated | True peak | LRA | Size |\n|---|---|---|---|---|---|---|---|---|---|\n')
    o.write('\n'.join(rows) + '\n\n')
    o.write('| Image | Size | File size |\n|---|---|---|\n' + '\n'.join(imgs) + '\n\n')
    o.write('Targets: runtime 1:45–1:55 (hard cap 1:59) · 3840×2160 and 1920×1080 · 30 fps · −14 LUFS integrated · ≤ −1 dBTP · AAC 320 kb/s, 48 kHz stereo.\n')
print(open(os.path.join(OUT, 'REPORT.md')).read())
